package com.illuminate.texaspoker.dao;

import com.illuminate.texaspoker.p058c.Banner;
import com.illuminate.texaspoker.p058c.Bill;
import com.illuminate.texaspoker.p058c.BuyInControlMsg;
import com.illuminate.texaspoker.p058c.ChatMsg;
import com.illuminate.texaspoker.p058c.ChatRoom;
import com.illuminate.texaspoker.p058c.ChatUser;
import com.illuminate.texaspoker.p058c.ClubAlbum;
import com.illuminate.texaspoker.p058c.ClubFundLog;
import com.illuminate.texaspoker.p058c.ClubMsg;
import com.illuminate.texaspoker.p058c.ClubRecord;
import com.illuminate.texaspoker.p058c.FriendAlbum;
import com.illuminate.texaspoker.p058c.FriendUser;
import com.illuminate.texaspoker.p058c.FriendshipChain;
import com.illuminate.texaspoker.p058c.GameRoom;
import com.illuminate.texaspoker.p058c.League;
import com.illuminate.texaspoker.p058c.LeagueClub;
import com.illuminate.texaspoker.p058c.LeagueMsg;
import com.illuminate.texaspoker.p058c.MessageMsg;
import com.illuminate.texaspoker.p058c.PokerHistory;
import com.illuminate.texaspoker.p058c.SellItem;
import com.illuminate.texaspoker.p058c.SocialMsg;
import com.illuminate.texaspoker.p058c.UserBill;
import java.util.Map;
import org.a.a.b.d;
import org.a.a.c;
import org.a.a.c.a;

/* renamed from: com.illuminate.texaspoker.dao.b */
public final class DaoSession extends c {
    public final ChatRoomDao f6426A;
    public final ChatUserDao f6427B;
    public final ClubAlbumDao f6428C;
    public final ClubFundLogDao f6429D;
    public final ClubMsgDao f6430E;
    public final ClubRecordDao f6431F;
    public final FriendAlbumDao f6432G;
    public final FriendshipChainDao f6433H;
    public final FriendUserDao f6434I;
    public final GameRoomDao f6435J;
    public final LeagueDao f6436K;
    public final LeagueClubDao f6437L;
    public final LeagueMsgDao f6438M;
    public final MessageMsgDao f6439N;
    public final PokerHistoryDao f6440O;
    public final SellItemDao f6441P;
    public final SocialMsgDao f6442Q;
    public final UserBillDao f6443R;
    public final a f6444a;
    public final a f6445b;
    public final a f6446c;
    public final a f6447d;
    public final a f6448e;
    public final a f6449f;
    public final a f6450g;
    public final a f6451h;
    public final a f6452i;
    public final a f6453j;
    public final a f6454k;
    public final a f6455l;
    public final a f6456m;
    public final a f6457n;
    public final a f6458o;
    public final a f6459p;
    public final a f6460q;
    public final a f6461r;
    public final a f6462s;
    public final a f6463t;
    public final a f6464u;
    public final a f6465v;
    public final BannerDao f6466w;
    public final BillDao f6467x;
    public final BuyInControlMsgDao f6468y;
    public final ChatMsgDao f6469z;

    public DaoSession(org.a.a.a.a aVar, d dVar, Map<Class<? extends org.a.a.a<?, ?>>, a> map) {
        super(aVar);
        this.f6444a = ((a) map.get(BannerDao.class)).a();
        this.f6444a.a(dVar);
        this.f6445b = ((a) map.get(BillDao.class)).a();
        this.f6445b.a(dVar);
        this.f6446c = ((a) map.get(BuyInControlMsgDao.class)).a();
        this.f6446c.a(dVar);
        this.f6447d = ((a) map.get(ChatMsgDao.class)).a();
        this.f6447d.a(dVar);
        this.f6448e = ((a) map.get(ChatRoomDao.class)).a();
        this.f6448e.a(dVar);
        this.f6449f = ((a) map.get(ChatUserDao.class)).a();
        this.f6449f.a(dVar);
        this.f6450g = ((a) map.get(ClubAlbumDao.class)).a();
        this.f6450g.a(dVar);
        this.f6451h = ((a) map.get(ClubFundLogDao.class)).a();
        this.f6451h.a(dVar);
        this.f6452i = ((a) map.get(ClubMsgDao.class)).a();
        this.f6452i.a(dVar);
        this.f6453j = ((a) map.get(ClubRecordDao.class)).a();
        this.f6453j.a(dVar);
        this.f6454k = ((a) map.get(FriendAlbumDao.class)).a();
        this.f6454k.a(dVar);
        this.f6455l = ((a) map.get(FriendshipChainDao.class)).a();
        this.f6455l.a(dVar);
        this.f6456m = ((a) map.get(FriendUserDao.class)).a();
        this.f6456m.a(dVar);
        this.f6457n = ((a) map.get(GameRoomDao.class)).a();
        this.f6457n.a(dVar);
        this.f6458o = ((a) map.get(LeagueDao.class)).a();
        this.f6458o.a(dVar);
        this.f6459p = ((a) map.get(LeagueClubDao.class)).a();
        this.f6459p.a(dVar);
        this.f6460q = ((a) map.get(LeagueMsgDao.class)).a();
        this.f6460q.a(dVar);
        this.f6461r = ((a) map.get(MessageMsgDao.class)).a();
        this.f6461r.a(dVar);
        this.f6462s = ((a) map.get(PokerHistoryDao.class)).a();
        this.f6462s.a(dVar);
        this.f6463t = ((a) map.get(SellItemDao.class)).a();
        this.f6463t.a(dVar);
        this.f6464u = ((a) map.get(SocialMsgDao.class)).a();
        this.f6464u.a(dVar);
        this.f6465v = ((a) map.get(UserBillDao.class)).a();
        this.f6465v.a(dVar);
        this.f6466w = new BannerDao(this.f6444a, this);
        this.f6467x = new BillDao(this.f6445b, this);
        this.f6468y = new BuyInControlMsgDao(this.f6446c, this);
        this.f6469z = new ChatMsgDao(this.f6447d, this);
        this.f6426A = new ChatRoomDao(this.f6448e, this);
        this.f6427B = new ChatUserDao(this.f6449f, this);
        this.f6428C = new ClubAlbumDao(this.f6450g, this);
        this.f6429D = new ClubFundLogDao(this.f6451h, this);
        this.f6430E = new ClubMsgDao(this.f6452i, this);
        this.f6431F = new ClubRecordDao(this.f6453j, this);
        this.f6432G = new FriendAlbumDao(this.f6454k, this);
        this.f6433H = new FriendshipChainDao(this.f6455l, this);
        this.f6434I = new FriendUserDao(this.f6456m, this);
        this.f6435J = new GameRoomDao(this.f6457n, this);
        this.f6436K = new LeagueDao(this.f6458o, this);
        this.f6437L = new LeagueClubDao(this.f6459p, this);
        this.f6438M = new LeagueMsgDao(this.f6460q, this);
        this.f6439N = new MessageMsgDao(this.f6461r, this);
        this.f6440O = new PokerHistoryDao(this.f6462s, this);
        this.f6441P = new SellItemDao(this.f6463t, this);
        this.f6442Q = new SocialMsgDao(this.f6464u, this);
        this.f6443R = new UserBillDao(this.f6465v, this);
        a(Banner.class, this.f6466w);
        a(Bill.class, this.f6467x);
        a(BuyInControlMsg.class, this.f6468y);
        a(ChatMsg.class, this.f6469z);
        a(ChatRoom.class, this.f6426A);
        a(ChatUser.class, this.f6427B);
        a(ClubAlbum.class, this.f6428C);
        a(ClubFundLog.class, this.f6429D);
        a(ClubMsg.class, this.f6430E);
        a(ClubRecord.class, this.f6431F);
        a(FriendAlbum.class, this.f6432G);
        a(FriendshipChain.class, this.f6433H);
        a(FriendUser.class, this.f6434I);
        a(GameRoom.class, this.f6435J);
        a(League.class, this.f6436K);
        a(LeagueClub.class, this.f6437L);
        a(LeagueMsg.class, this.f6438M);
        a(MessageMsg.class, this.f6439N);
        a(PokerHistory.class, this.f6440O);
        a(SellItem.class, this.f6441P);
        a(SocialMsg.class, this.f6442Q);
        a(UserBill.class, this.f6443R);
    }

    public final BuyInControlMsgDao m3917a() {
        return this.f6468y;
    }

    public final FriendUserDao m3918b() {
        return this.f6434I;
    }
}
