package com.illuminate.texaspoker.p057b;

import android.content.Context;
import com.illuminate.texaspoker.dao.DaoMaster.DaoMaster;

/* renamed from: com.illuminate.texaspoker.b.l */
public final class DBOpenHelper extends DaoMaster {
    public DBOpenHelper(Context context, String str) {
        super(context, str);
    }

    /* JADX WARNING: inconsistent code. */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final void m3635a(org.a.a.a.a r4, int r5, int r6) {
        /*
        r3 = this;
        r0 = "greenDAO";
        r1 = new java.lang.StringBuilder;
        r2 = "Upgrading schema from version ";
        r1.<init>(r2);
        r1 = r1.append(r5);
        r2 = " to ";
        r1 = r1.append(r2);
        r1 = r1.append(r6);
        r1 = r1.toString();
        android.util.Log.i(r0, r1);
        switch(r5) {
            case 1: goto L_0x0022;
            case 2: goto L_0x00ae;
            case 3: goto L_0x0412;
            case 4: goto L_0x044a;
            default: goto L_0x0021;
        };
    L_0x0021:
        return;
    L_0x0022:
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE POKER_HISTORY ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.PokerHistoryDao.Properties.f6364A;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE POKER_HISTORY ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.PokerHistoryDao.Properties.f6365B;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE POKER_HISTORY ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.PokerHistoryDao.Properties.f6366C;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE GAME_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.GameRoomDao.Properties.f6286G;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE GAME_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.GameRoomDao.Properties.f6287H;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
    L_0x00ae:
        r0 = new java.lang.StringBuilder;
        r1 = "CREATE TABLE LEAGUE ('";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6329a;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER PRIMARY KEY,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6330b;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6331c;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6332d;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6333e;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6334f;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6335g;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6336h;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6338j;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueDao.Properties.f6337i;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER);";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "CREATE TABLE LEAGUE_CLUB ('";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6319a;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER PRIMARY KEY,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6320b;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6321c;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6322d;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6323e;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6324f;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6325g;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6326h;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueClubDao.Properties.f6327i;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT);";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "CREATE TABLE LEAGUE_MSG ('";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6339a;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER PRIMARY KEY,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6340b;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6341c;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6342d;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6343e;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6344f;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6345g;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6346h;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6347i;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6348j;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6349k;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT,'";
        r0 = r0.append(r1);
        r1 = com.illuminate.texaspoker.dao.LeagueMsgDao.Properties.f6350l;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT);";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE CLUB_MSG ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.ClubMsgDao.Properties.f6225k;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE CHAT_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.ChatRoomDao.Properties.f6163U;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE GAME_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.GameRoomDao.Properties.f6288I;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE GAME_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.GameRoomDao.Properties.f6289J;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE USER_BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.UserBillDao.Properties.f6423k;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE USER_BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.UserBillDao.Properties.f6424l;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BillDao.Properties.f6073Q;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BillDao.Properties.f6074R;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BillDao.Properties.f6075S;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE CHAT_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.ChatRoomDao.Properties.f6164V;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BUY_IN_CONTROL_MSG ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BuyInControlMsgDao.Properties.f6114j;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BUY_IN_CONTROL_MSG ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BuyInControlMsgDao.Properties.f6115k;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BUY_IN_CONTROL_MSG ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BuyInControlMsgDao.Properties.f6116l;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' INTEGER;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BUY_IN_CONTROL_MSG ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BuyInControlMsgDao.Properties.f6117m;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
    L_0x0412:
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE GAME_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.GameRoomDao.Properties.f6290K;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BillDao.Properties.f6076T;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
    L_0x044a:
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE GAME_ROOM ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.GameRoomDao.Properties.f6291L;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        r0 = new java.lang.StringBuilder;
        r1 = "ALTER TABLE BILL ADD COLUMN '";
        r0.<init>(r1);
        r1 = com.illuminate.texaspoker.dao.BillDao.Properties.f6077U;
        r1 = r1.e;
        r0 = r0.append(r1);
        r1 = "' TEXT;";
        r0 = r0.append(r1);
        r0 = r0.toString();
        r4.a(r0);
        goto L_0x0021;
        */
        throw new UnsupportedOperationException("Method not decompiled: com.illuminate.texaspoker.b.l.a(org.a.a.a.a, int, int):void");
    }
}
