package com.illuminate.texaspoker;

import android.support.v7.appcompat.C0184R;
import android.support.v7.cardview.C0185R;

/* renamed from: com.illuminate.texaspoker.a */
public final class R {

    /* renamed from: com.illuminate.texaspoker.a.a */
    public static final class R {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetEndWithActions = 25;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_contentInsetStartWithNavigation = 24;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 26;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 28;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 27;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] AlertDialog;
        public static final int AlertDialog_android_layout = 0;
        public static final int AlertDialog_buttonPanelSideLayout = 1;
        public static final int AlertDialog_listItemLayout = 5;
        public static final int AlertDialog_listLayout = 2;
        public static final int AlertDialog_multiChoiceItemLayout = 3;
        public static final int AlertDialog_showTitle = 6;
        public static final int AlertDialog_singleChoiceItemLayout = 4;
        public static final int[] AppCompatImageView;
        public static final int AppCompatImageView_android_src = 0;
        public static final int AppCompatImageView_srcCompat = 1;
        public static final int[] AppCompatSeekBar;
        public static final int AppCompatSeekBar_android_thumb = 0;
        public static final int AppCompatSeekBar_tickMark = 1;
        public static final int AppCompatSeekBar_tickMarkTint = 2;
        public static final int AppCompatSeekBar_tickMarkTintMode = 3;
        public static final int[] AppCompatTextHelper;
        public static final int AppCompatTextHelper_android_drawableBottom = 2;
        public static final int AppCompatTextHelper_android_drawableEnd = 6;
        public static final int AppCompatTextHelper_android_drawableLeft = 3;
        public static final int AppCompatTextHelper_android_drawableRight = 4;
        public static final int AppCompatTextHelper_android_drawableStart = 5;
        public static final int AppCompatTextHelper_android_drawableTop = 1;
        public static final int AppCompatTextHelper_android_textAppearance = 0;
        public static final int[] AppCompatTextView;
        public static final int AppCompatTextView_android_textAppearance = 0;
        public static final int AppCompatTextView_textAllCaps = 1;
        public static final int[] AppCompatTheme;
        public static final int AppCompatTheme_actionBarDivider = 23;
        public static final int AppCompatTheme_actionBarItemBackground = 24;
        public static final int AppCompatTheme_actionBarPopupTheme = 17;
        public static final int AppCompatTheme_actionBarSize = 22;
        public static final int AppCompatTheme_actionBarSplitStyle = 19;
        public static final int AppCompatTheme_actionBarStyle = 18;
        public static final int AppCompatTheme_actionBarTabBarStyle = 13;
        public static final int AppCompatTheme_actionBarTabStyle = 12;
        public static final int AppCompatTheme_actionBarTabTextStyle = 14;
        public static final int AppCompatTheme_actionBarTheme = 20;
        public static final int AppCompatTheme_actionBarWidgetTheme = 21;
        public static final int AppCompatTheme_actionButtonStyle = 50;
        public static final int AppCompatTheme_actionDropDownStyle = 46;
        public static final int AppCompatTheme_actionMenuTextAppearance = 25;
        public static final int AppCompatTheme_actionMenuTextColor = 26;
        public static final int AppCompatTheme_actionModeBackground = 29;
        public static final int AppCompatTheme_actionModeCloseButtonStyle = 28;
        public static final int AppCompatTheme_actionModeCloseDrawable = 31;
        public static final int AppCompatTheme_actionModeCopyDrawable = 33;
        public static final int AppCompatTheme_actionModeCutDrawable = 32;
        public static final int AppCompatTheme_actionModeFindDrawable = 37;
        public static final int AppCompatTheme_actionModePasteDrawable = 34;
        public static final int AppCompatTheme_actionModePopupWindowStyle = 39;
        public static final int AppCompatTheme_actionModeSelectAllDrawable = 35;
        public static final int AppCompatTheme_actionModeShareDrawable = 36;
        public static final int AppCompatTheme_actionModeSplitBackground = 30;
        public static final int AppCompatTheme_actionModeStyle = 27;
        public static final int AppCompatTheme_actionModeWebSearchDrawable = 38;
        public static final int AppCompatTheme_actionOverflowButtonStyle = 15;
        public static final int AppCompatTheme_actionOverflowMenuStyle = 16;
        public static final int AppCompatTheme_activityChooserViewStyle = 58;
        public static final int AppCompatTheme_alertDialogButtonGroupStyle = 94;
        public static final int AppCompatTheme_alertDialogCenterButtons = 95;
        public static final int AppCompatTheme_alertDialogStyle = 93;
        public static final int AppCompatTheme_alertDialogTheme = 96;
        public static final int AppCompatTheme_android_windowAnimationStyle = 1;
        public static final int AppCompatTheme_android_windowIsFloating = 0;
        public static final int AppCompatTheme_autoCompleteTextViewStyle = 101;
        public static final int AppCompatTheme_borderlessButtonStyle = 55;
        public static final int AppCompatTheme_buttonBarButtonStyle = 52;
        public static final int AppCompatTheme_buttonBarNegativeButtonStyle = 99;
        public static final int AppCompatTheme_buttonBarNeutralButtonStyle = 100;
        public static final int AppCompatTheme_buttonBarPositiveButtonStyle = 98;
        public static final int AppCompatTheme_buttonBarStyle = 51;
        public static final int AppCompatTheme_buttonStyle = 102;
        public static final int AppCompatTheme_buttonStyleSmall = 103;
        public static final int AppCompatTheme_checkboxStyle = 104;
        public static final int AppCompatTheme_checkedTextViewStyle = 105;
        public static final int AppCompatTheme_colorAccent = 85;
        public static final int AppCompatTheme_colorBackgroundFloating = 92;
        public static final int AppCompatTheme_colorButtonNormal = 89;
        public static final int AppCompatTheme_colorControlActivated = 87;
        public static final int AppCompatTheme_colorControlHighlight = 88;
        public static final int AppCompatTheme_colorControlNormal = 86;
        public static final int AppCompatTheme_colorPrimary = 83;
        public static final int AppCompatTheme_colorPrimaryDark = 84;
        public static final int AppCompatTheme_colorSwitchThumbNormal = 90;
        public static final int AppCompatTheme_controlBackground = 91;
        public static final int AppCompatTheme_dialogPreferredPadding = 44;
        public static final int AppCompatTheme_dialogTheme = 43;
        public static final int AppCompatTheme_dividerHorizontal = 57;
        public static final int AppCompatTheme_dividerVertical = 56;
        public static final int AppCompatTheme_dropDownListViewStyle = 75;
        public static final int AppCompatTheme_dropdownListPreferredItemHeight = 47;
        public static final int AppCompatTheme_editTextBackground = 64;
        public static final int AppCompatTheme_editTextColor = 63;
        public static final int AppCompatTheme_editTextStyle = 106;
        public static final int AppCompatTheme_homeAsUpIndicator = 49;
        public static final int AppCompatTheme_imageButtonStyle = 65;
        public static final int AppCompatTheme_listChoiceBackgroundIndicator = 82;
        public static final int AppCompatTheme_listDividerAlertDialog = 45;
        public static final int AppCompatTheme_listMenuViewStyle = 114;
        public static final int AppCompatTheme_listPopupWindowStyle = 76;
        public static final int AppCompatTheme_listPreferredItemHeight = 70;
        public static final int AppCompatTheme_listPreferredItemHeightLarge = 72;
        public static final int AppCompatTheme_listPreferredItemHeightSmall = 71;
        public static final int AppCompatTheme_listPreferredItemPaddingLeft = 73;
        public static final int AppCompatTheme_listPreferredItemPaddingRight = 74;
        public static final int AppCompatTheme_panelBackground = 79;
        public static final int AppCompatTheme_panelMenuListTheme = 81;
        public static final int AppCompatTheme_panelMenuListWidth = 80;
        public static final int AppCompatTheme_popupMenuStyle = 61;
        public static final int AppCompatTheme_popupWindowStyle = 62;
        public static final int AppCompatTheme_radioButtonStyle = 107;
        public static final int AppCompatTheme_ratingBarStyle = 108;
        public static final int AppCompatTheme_ratingBarStyleIndicator = 109;
        public static final int AppCompatTheme_ratingBarStyleSmall = 110;
        public static final int AppCompatTheme_searchViewStyle = 69;
        public static final int AppCompatTheme_seekBarStyle = 111;
        public static final int AppCompatTheme_selectableItemBackground = 53;
        public static final int AppCompatTheme_selectableItemBackgroundBorderless = 54;
        public static final int AppCompatTheme_spinnerDropDownItemStyle = 48;
        public static final int AppCompatTheme_spinnerStyle = 112;
        public static final int AppCompatTheme_switchStyle = 113;
        public static final int AppCompatTheme_textAppearanceLargePopupMenu = 40;
        public static final int AppCompatTheme_textAppearanceListItem = 77;
        public static final int AppCompatTheme_textAppearanceListItemSmall = 78;
        public static final int AppCompatTheme_textAppearancePopupMenuHeader = 42;
        public static final int AppCompatTheme_textAppearanceSearchResultSubtitle = 67;
        public static final int AppCompatTheme_textAppearanceSearchResultTitle = 66;
        public static final int AppCompatTheme_textAppearanceSmallPopupMenu = 41;
        public static final int AppCompatTheme_textColorAlertDialogListItem = 97;
        public static final int AppCompatTheme_textColorSearchUrl = 68;
        public static final int AppCompatTheme_toolbarNavigationButtonStyle = 60;
        public static final int AppCompatTheme_toolbarStyle = 59;
        public static final int AppCompatTheme_windowActionBar = 2;
        public static final int AppCompatTheme_windowActionBarOverlay = 4;
        public static final int AppCompatTheme_windowActionModeOverlay = 5;
        public static final int AppCompatTheme_windowFixedHeightMajor = 9;
        public static final int AppCompatTheme_windowFixedHeightMinor = 7;
        public static final int AppCompatTheme_windowFixedWidthMajor = 6;
        public static final int AppCompatTheme_windowFixedWidthMinor = 8;
        public static final int AppCompatTheme_windowMinWidthMajor = 10;
        public static final int AppCompatTheme_windowMinWidthMinor = 11;
        public static final int AppCompatTheme_windowNoTitle = 3;
        public static final int[] ButtonBarLayout;
        public static final int ButtonBarLayout_allowStacking = 0;
        public static final int[] CardView;
        public static final int CardView_android_minHeight = 1;
        public static final int CardView_android_minWidth = 0;
        public static final int CardView_cardBackgroundColor = 2;
        public static final int CardView_cardCornerRadius = 3;
        public static final int CardView_cardElevation = 4;
        public static final int CardView_cardMaxElevation = 5;
        public static final int CardView_cardPreventCornerOverlap = 7;
        public static final int CardView_cardUseCompatPadding = 6;
        public static final int CardView_contentPadding = 8;
        public static final int CardView_contentPaddingBottom = 12;
        public static final int CardView_contentPaddingLeft = 9;
        public static final int CardView_contentPaddingRight = 10;
        public static final int CardView_contentPaddingTop = 11;
        public static final int[] ColorStateListItem;
        public static final int ColorStateListItem_alpha = 2;
        public static final int ColorStateListItem_android_alpha = 1;
        public static final int ColorStateListItem_android_color = 0;
        public static final int[] CompoundButton;
        public static final int CompoundButton_android_button = 0;
        public static final int CompoundButton_buttonTint = 1;
        public static final int CompoundButton_buttonTintMode = 2;
        public static final int[] DrawerArrowToggle;
        public static final int DrawerArrowToggle_arrowHeadLength = 4;
        public static final int DrawerArrowToggle_arrowShaftLength = 5;
        public static final int DrawerArrowToggle_barLength = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int[] GenericDraweeHierarchy;
        public static final int GenericDraweeHierarchy_actualImageScaleType = 11;
        public static final int GenericDraweeHierarchy_backgroundImage = 12;
        public static final int GenericDraweeHierarchy_fadeDuration = 0;
        public static final int GenericDraweeHierarchy_failureImage = 6;
        public static final int GenericDraweeHierarchy_failureImageScaleType = 7;
        public static final int GenericDraweeHierarchy_overlayImage = 13;
        public static final int GenericDraweeHierarchy_placeholderImage = 2;
        public static final int GenericDraweeHierarchy_placeholderImageScaleType = 3;
        public static final int GenericDraweeHierarchy_pressedStateOverlayImage = 14;
        public static final int GenericDraweeHierarchy_progressBarAutoRotateInterval = 10;
        public static final int GenericDraweeHierarchy_progressBarImage = 8;
        public static final int GenericDraweeHierarchy_progressBarImageScaleType = 9;
        public static final int GenericDraweeHierarchy_retryImage = 4;
        public static final int GenericDraweeHierarchy_retryImageScaleType = 5;
        public static final int GenericDraweeHierarchy_roundAsCircle = 15;
        public static final int GenericDraweeHierarchy_roundBottomLeft = 20;
        public static final int GenericDraweeHierarchy_roundBottomRight = 19;
        public static final int GenericDraweeHierarchy_roundTopLeft = 17;
        public static final int GenericDraweeHierarchy_roundTopRight = 18;
        public static final int GenericDraweeHierarchy_roundWithOverlayColor = 21;
        public static final int GenericDraweeHierarchy_roundedCornerRadius = 16;
        public static final int GenericDraweeHierarchy_roundingBorderColor = 23;
        public static final int GenericDraweeHierarchy_roundingBorderPadding = 24;
        public static final int GenericDraweeHierarchy_roundingBorderWidth = 22;
        public static final int GenericDraweeHierarchy_viewAspectRatio = 1;
        public static final int[] HorizontalListView;
        public static final int HorizontalListView_android_divider = 1;
        public static final int HorizontalListView_android_fadingEdgeLength = 0;
        public static final int HorizontalListView_android_requiresFadingEdge = 2;
        public static final int HorizontalListView_dividerWidth = 3;
        public static final int[] LinearLayoutCompat;
        public static final int[] LinearLayoutCompat_Layout;
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int[] ListPopupWindow;
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int MenuView_subMenuArrow = 8;
        public static final int[] PopupWindow;
        public static final int[] PopupWindowBackgroundState;
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupAnimationStyle = 1;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 2;
        public static final int[] RangeSeekBar;
        public static final int RangeSeekBar_autoMoveDuration = 10;
        public static final int RangeSeekBar_leftCursorBackground = 3;
        public static final int RangeSeekBar_markTextArray = 5;
        public static final int RangeSeekBar_rightCursorBackground = 4;
        public static final int RangeSeekBar_seekBarColorNormal = 8;
        public static final int RangeSeekBar_seekBarColorSelected = 9;
        public static final int RangeSeekBar_seekBarHeight = 0;
        public static final int RangeSeekBar_spaceBetween = 2;
        public static final int RangeSeekBar_textColorNormal = 6;
        public static final int RangeSeekBar_textColorSelected = 7;
        public static final int RangeSeekBar_textSize = 1;
        public static final int[] RecycleListView;
        public static final int RecycleListView_paddingBottomNoButtons = 0;
        public static final int RecycleListView_paddingTopNoTitle = 1;
        public static final int[] RefreshLayout;
        public static final int RefreshLayout_refresh_content = 1;
        public static final int RefreshLayout_refresh_duration_to_close = 4;
        public static final int RefreshLayout_refresh_duration_to_close_header = 5;
        public static final int RefreshLayout_refresh_header = 0;
        public static final int RefreshLayout_refresh_keep_header_when_refresh = 7;
        public static final int RefreshLayout_refresh_pull_to_fresh = 6;
        public static final int RefreshLayout_refresh_ratio_of_header_height_to_refresh = 3;
        public static final int RefreshLayout_refresh_resistance = 2;
        public static final int[] SearchView;
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 8;
        public static final int SearchView_commitIcon = 13;
        public static final int SearchView_defaultQueryHint = 7;
        public static final int SearchView_goIcon = 9;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 15;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchHintIcon = 11;
        public static final int SearchView_searchIcon = 10;
        public static final int SearchView_submitBackground = 16;
        public static final int SearchView_suggestionRowLayout = 14;
        public static final int SearchView_voiceIcon = 12;
        public static final int[] SimpleDraweeView;
        public static final int SimpleDraweeView_actualImageUri = 0;
        public static final int[] Spinner;
        public static final int Spinner_android_dropDownWidth = 3;
        public static final int Spinner_android_entries = 0;
        public static final int Spinner_android_popupBackground = 1;
        public static final int Spinner_android_prompt = 2;
        public static final int Spinner_popupTheme = 4;
        public static final int[] SwipeBackLayout;
        public static final int SwipeBackLayout_edge_flag = 1;
        public static final int SwipeBackLayout_edge_size = 0;
        public static final int SwipeBackLayout_shadow_bottom = 4;
        public static final int SwipeBackLayout_shadow_left = 2;
        public static final int SwipeBackLayout_shadow_right = 3;
        public static final int[] SwitchCompat;
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 13;
        public static final int SwitchCompat_splitTrack = 12;
        public static final int SwitchCompat_switchMinWidth = 10;
        public static final int SwitchCompat_switchPadding = 11;
        public static final int SwitchCompat_switchTextAppearance = 9;
        public static final int SwitchCompat_thumbTextPadding = 8;
        public static final int SwitchCompat_thumbTint = 3;
        public static final int SwitchCompat_thumbTintMode = 4;
        public static final int SwitchCompat_track = 5;
        public static final int SwitchCompat_trackTint = 6;
        public static final int SwitchCompat_trackTintMode = 7;
        public static final int[] TextAppearance;
        public static final int TextAppearance_android_shadowColor = 5;
        public static final int TextAppearance_android_shadowDx = 6;
        public static final int TextAppearance_android_shadowDy = 7;
        public static final int TextAppearance_android_shadowRadius = 8;
        public static final int TextAppearance_android_textColor = 3;
        public static final int TextAppearance_android_textColorHint = 4;
        public static final int TextAppearance_android_textSize = 0;
        public static final int TextAppearance_android_textStyle = 2;
        public static final int TextAppearance_android_typeface = 1;
        public static final int TextAppearance_textAllCaps = 9;
        public static final int[] Toolbar;
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_buttonGravity = 21;
        public static final int Toolbar_collapseContentDescription = 23;
        public static final int Toolbar_collapseIcon = 22;
        public static final int Toolbar_contentInsetEnd = 6;
        public static final int Toolbar_contentInsetEndWithActions = 10;
        public static final int Toolbar_contentInsetLeft = 7;
        public static final int Toolbar_contentInsetRight = 8;
        public static final int Toolbar_contentInsetStart = 5;
        public static final int Toolbar_contentInsetStartWithNavigation = 9;
        public static final int Toolbar_logo = 4;
        public static final int Toolbar_logoDescription = 26;
        public static final int Toolbar_maxButtonHeight = 20;
        public static final int Toolbar_navigationContentDescription = 25;
        public static final int Toolbar_navigationIcon = 24;
        public static final int Toolbar_popupTheme = 11;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 13;
        public static final int Toolbar_subtitleTextColor = 28;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMargin = 14;
        public static final int Toolbar_titleMarginBottom = 18;
        public static final int Toolbar_titleMarginEnd = 16;
        public static final int Toolbar_titleMarginStart = 15;
        public static final int Toolbar_titleMarginTop = 17;
        public static final int Toolbar_titleMargins = 19;
        public static final int Toolbar_titleTextAppearance = 12;
        public static final int Toolbar_titleTextColor = 27;
        public static final int[] View;
        public static final int[] ViewBackgroundHelper;
        public static final int ViewBackgroundHelper_android_background = 0;
        public static final int ViewBackgroundHelper_backgroundTint = 1;
        public static final int ViewBackgroundHelper_backgroundTintMode = 2;
        public static final int[] ViewStubCompat;
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 1;
        public static final int View_android_theme = 0;
        public static final int View_paddingEnd = 3;
        public static final int View_paddingStart = 2;
        public static final int View_theme = 4;
        public static final int[] com_facebook_like_view;
        public static final int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
        public static final int com_facebook_like_view_com_facebook_foreground_color = 0;
        public static final int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
        public static final int com_facebook_like_view_com_facebook_object_id = 1;
        public static final int com_facebook_like_view_com_facebook_object_type = 2;
        public static final int com_facebook_like_view_com_facebook_style = 3;
        public static final int[] com_facebook_login_view;
        public static final int com_facebook_login_view_com_facebook_confirm_logout = 0;
        public static final int com_facebook_login_view_com_facebook_login_text = 1;
        public static final int com_facebook_login_view_com_facebook_logout_text = 2;
        public static final int com_facebook_login_view_com_facebook_tooltip_mode = 3;
        public static final int[] com_facebook_profile_picture_view;
        public static final int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
        public static final int com_facebook_profile_picture_view_com_facebook_preset_size = 0;

        static {
            ActionBar = new int[]{C0184R.attr.height, C0184R.attr.title, C0184R.attr.navigationMode, C0184R.attr.displayOptions, C0184R.attr.subtitle, C0184R.attr.titleTextStyle, C0184R.attr.subtitleTextStyle, C0184R.attr.icon, C0184R.attr.logo, C0184R.attr.divider, C0184R.attr.background, C0184R.attr.backgroundStacked, C0184R.attr.backgroundSplit, C0184R.attr.customNavigationLayout, C0184R.attr.homeLayout, C0184R.attr.progressBarStyle, C0184R.attr.indeterminateProgressStyle, C0184R.attr.progressBarPadding, C0184R.attr.itemPadding, C0184R.attr.hideOnContentScroll, C0184R.attr.contentInsetStart, C0184R.attr.contentInsetEnd, C0184R.attr.contentInsetLeft, C0184R.attr.contentInsetRight, C0184R.attr.contentInsetStartWithNavigation, C0184R.attr.contentInsetEndWithActions, C0184R.attr.elevation, C0184R.attr.popupTheme, C0184R.attr.homeAsUpIndicator};
            int[] iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16842931;
            ActionBarLayout = iArr;
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[com_facebook_login_view_com_facebook_confirm_logout];
            ActionMode = new int[]{C0184R.attr.height, C0184R.attr.titleTextStyle, C0184R.attr.subtitleTextStyle, C0184R.attr.background, C0184R.attr.backgroundSplit, C0184R.attr.closeItemLayout};
            ActivityChooserView = new int[]{C0184R.attr.initialActivityCount, C0184R.attr.expandActivityOverflowButtonDrawable};
            AlertDialog = new int[]{16842994, C0184R.attr.buttonPanelSideLayout, C0184R.attr.listLayout, C0184R.attr.multiChoiceItemLayout, C0184R.attr.singleChoiceItemLayout, C0184R.attr.listItemLayout, C0184R.attr.showTitle};
            AppCompatImageView = new int[]{16843033, C0184R.attr.srcCompat};
            AppCompatSeekBar = new int[]{16843074, C0184R.attr.tickMark, C0184R.attr.tickMarkTint, C0184R.attr.tickMarkTintMode};
            AppCompatTextHelper = new int[]{16842804, 16843117, 16843118, 16843119, 16843120, 16843666, 16843667};
            AppCompatTextView = new int[]{16842804, C0184R.attr.textAllCaps};
            AppCompatTheme = new int[]{16842839, 16842926, C0184R.attr.windowActionBar, C0184R.attr.windowNoTitle, C0184R.attr.windowActionBarOverlay, C0184R.attr.windowActionModeOverlay, C0184R.attr.windowFixedWidthMajor, C0184R.attr.windowFixedHeightMinor, C0184R.attr.windowFixedWidthMinor, C0184R.attr.windowFixedHeightMajor, C0184R.attr.windowMinWidthMajor, C0184R.attr.windowMinWidthMinor, C0184R.attr.actionBarTabStyle, C0184R.attr.actionBarTabBarStyle, C0184R.attr.actionBarTabTextStyle, C0184R.attr.actionOverflowButtonStyle, C0184R.attr.actionOverflowMenuStyle, C0184R.attr.actionBarPopupTheme, C0184R.attr.actionBarStyle, C0184R.attr.actionBarSplitStyle, C0184R.attr.actionBarTheme, C0184R.attr.actionBarWidgetTheme, C0184R.attr.actionBarSize, C0184R.attr.actionBarDivider, C0184R.attr.actionBarItemBackground, C0184R.attr.actionMenuTextAppearance, C0184R.attr.actionMenuTextColor, C0184R.attr.actionModeStyle, C0184R.attr.actionModeCloseButtonStyle, C0184R.attr.actionModeBackground, C0184R.attr.actionModeSplitBackground, C0184R.attr.actionModeCloseDrawable, C0184R.attr.actionModeCutDrawable, C0184R.attr.actionModeCopyDrawable, C0184R.attr.actionModePasteDrawable, C0184R.attr.actionModeSelectAllDrawable, C0184R.attr.actionModeShareDrawable, C0184R.attr.actionModeFindDrawable, C0184R.attr.actionModeWebSearchDrawable, C0184R.attr.actionModePopupWindowStyle, C0184R.attr.textAppearanceLargePopupMenu, C0184R.attr.textAppearanceSmallPopupMenu, C0184R.attr.textAppearancePopupMenuHeader, C0184R.attr.dialogTheme, C0184R.attr.dialogPreferredPadding, C0184R.attr.listDividerAlertDialog, C0184R.attr.actionDropDownStyle, C0184R.attr.dropdownListPreferredItemHeight, C0184R.attr.spinnerDropDownItemStyle, C0184R.attr.homeAsUpIndicator, C0184R.attr.actionButtonStyle, C0184R.attr.buttonBarStyle, C0184R.attr.buttonBarButtonStyle, C0184R.attr.selectableItemBackground, C0184R.attr.selectableItemBackgroundBorderless, C0184R.attr.borderlessButtonStyle, C0184R.attr.dividerVertical, C0184R.attr.dividerHorizontal, C0184R.attr.activityChooserViewStyle, C0184R.attr.toolbarStyle, C0184R.attr.toolbarNavigationButtonStyle, C0184R.attr.popupMenuStyle, C0184R.attr.popupWindowStyle, C0184R.attr.editTextColor, C0184R.attr.editTextBackground, C0184R.attr.imageButtonStyle, C0184R.attr.textAppearanceSearchResultTitle, C0184R.attr.textAppearanceSearchResultSubtitle, C0184R.attr.textColorSearchUrl, C0184R.attr.searchViewStyle, C0184R.attr.listPreferredItemHeight, C0184R.attr.listPreferredItemHeightSmall, C0184R.attr.listPreferredItemHeightLarge, C0184R.attr.listPreferredItemPaddingLeft, C0184R.attr.listPreferredItemPaddingRight, C0184R.attr.dropDownListViewStyle, C0184R.attr.listPopupWindowStyle, C0184R.attr.textAppearanceListItem, C0184R.attr.textAppearanceListItemSmall, C0184R.attr.panelBackground, C0184R.attr.panelMenuListWidth, C0184R.attr.panelMenuListTheme, C0184R.attr.listChoiceBackgroundIndicator, C0184R.attr.colorPrimary, C0184R.attr.colorPrimaryDark, C0184R.attr.colorAccent, C0184R.attr.colorControlNormal, C0184R.attr.colorControlActivated, C0184R.attr.colorControlHighlight, C0184R.attr.colorButtonNormal, C0184R.attr.colorSwitchThumbNormal, C0184R.attr.controlBackground, C0184R.attr.colorBackgroundFloating, C0184R.attr.alertDialogStyle, C0184R.attr.alertDialogButtonGroupStyle, C0184R.attr.alertDialogCenterButtons, C0184R.attr.alertDialogTheme, C0184R.attr.textColorAlertDialogListItem, C0184R.attr.buttonBarPositiveButtonStyle, C0184R.attr.buttonBarNegativeButtonStyle, C0184R.attr.buttonBarNeutralButtonStyle, C0184R.attr.autoCompleteTextViewStyle, C0184R.attr.buttonStyle, C0184R.attr.buttonStyleSmall, C0184R.attr.checkboxStyle, C0184R.attr.checkedTextViewStyle, C0184R.attr.editTextStyle, C0184R.attr.radioButtonStyle, C0184R.attr.ratingBarStyle, C0184R.attr.ratingBarStyleIndicator, C0184R.attr.ratingBarStyleSmall, C0184R.attr.seekBarStyle, C0184R.attr.spinnerStyle, C0184R.attr.switchStyle, C0184R.attr.listMenuViewStyle};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0184R.attr.allowStacking;
            ButtonBarLayout = iArr;
            CardView = new int[]{16843071, 16843072, C0185R.attr.cardBackgroundColor, C0185R.attr.cardCornerRadius, C0185R.attr.cardElevation, C0185R.attr.cardMaxElevation, C0185R.attr.cardUseCompatPadding, C0185R.attr.cardPreventCornerOverlap, C0185R.attr.contentPadding, C0185R.attr.contentPaddingLeft, C0185R.attr.contentPaddingRight, C0185R.attr.contentPaddingTop, C0185R.attr.contentPaddingBottom};
            ColorStateListItem = new int[]{16843173, 16843551, C0184R.attr.alpha};
            CompoundButton = new int[]{16843015, C0184R.attr.buttonTint, C0184R.attr.buttonTintMode};
            DrawerArrowToggle = new int[]{C0184R.attr.color, C0184R.attr.spinBars, C0184R.attr.drawableSize, C0184R.attr.gapBetweenBars, C0184R.attr.arrowHeadLength, C0184R.attr.arrowShaftLength, C0184R.attr.barLength, C0184R.attr.thickness};
            GenericDraweeHierarchy = new int[]{2130772149, 2130772150, 2130772151, 2130772152, 2130772153, 2130772154, 2130772155, 2130772156, 2130772157, 2130772158, 2130772159, 2130772160, 2130772161, 2130772162, 2130772163, 2130772164, 2130772165, 2130772166, 2130772167, 2130772168, 2130772169, 2130772170, 2130772171, 2130772172, 2130772173};
            HorizontalListView = new int[]{16842976, 16843049, 16843685, 2130772174};
            LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, C0184R.attr.divider, C0184R.attr.measureWithLargestChild, C0184R.attr.showDividers, C0184R.attr.dividerPadding};
            LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
            ListPopupWindow = new int[]{16843436, 16843437};
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, C0184R.attr.showAsAction, C0184R.attr.actionLayout, C0184R.attr.actionViewClass, C0184R.attr.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, C0184R.attr.preserveIconSpacing, C0184R.attr.subMenuArrow};
            PopupWindow = new int[]{16843126, 16843465, C0184R.attr.overlapAnchor};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = C0184R.attr.state_above_anchor;
            PopupWindowBackgroundState = iArr;
            RangeSeekBar = new int[]{2130772186, 2130772187, 2130772188, 2130772189, 2130772190, 2130772191, 2130772192, 2130772193, 2130772194, 2130772195, 2130772196};
            RecycleListView = new int[]{C0184R.attr.paddingBottomNoButtons, C0184R.attr.paddingTopNoTitle};
            RefreshLayout = new int[]{2130772199, 2130772200, 2130772201, 2130772202, 2130772203, 2130772204, 2130772205, 2130772206};
            SearchView = new int[]{16842970, 16843039, 16843296, 16843364, C0184R.attr.layout, C0184R.attr.iconifiedByDefault, C0184R.attr.queryHint, C0184R.attr.defaultQueryHint, C0184R.attr.closeIcon, C0184R.attr.goIcon, C0184R.attr.searchIcon, C0184R.attr.searchHintIcon, C0184R.attr.voiceIcon, C0184R.attr.commitIcon, C0184R.attr.suggestionRowLayout, C0184R.attr.queryBackground, C0184R.attr.submitBackground};
            iArr = new int[com_facebook_profile_picture_view_com_facebook_is_cropped];
            iArr[com_facebook_login_view_com_facebook_confirm_logout] = 2130772220;
            SimpleDraweeView = iArr;
            Spinner = new int[]{16842930, 16843126, 16843131, 16843362, C0184R.attr.popupTheme};
            SwipeBackLayout = new int[]{2130772221, 2130772222, 2130772223, 2130772224, 2130772225};
            SwitchCompat = new int[]{16843044, 16843045, 16843074, C0184R.attr.thumbTint, C0184R.attr.thumbTintMode, C0184R.attr.track, C0184R.attr.trackTint, C0184R.attr.trackTintMode, C0184R.attr.thumbTextPadding, C0184R.attr.switchTextAppearance, C0184R.attr.switchMinWidth, C0184R.attr.switchPadding, C0184R.attr.splitTrack, C0184R.attr.showText};
            TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16842906, 16843105, 16843106, 16843107, 16843108, C0184R.attr.textAllCaps};
            Toolbar = new int[]{16842927, 16843072, C0184R.attr.title, C0184R.attr.subtitle, C0184R.attr.logo, C0184R.attr.contentInsetStart, C0184R.attr.contentInsetEnd, C0184R.attr.contentInsetLeft, C0184R.attr.contentInsetRight, C0184R.attr.contentInsetStartWithNavigation, C0184R.attr.contentInsetEndWithActions, C0184R.attr.popupTheme, C0184R.attr.titleTextAppearance, C0184R.attr.subtitleTextAppearance, C0184R.attr.titleMargin, C0184R.attr.titleMarginStart, C0184R.attr.titleMarginEnd, C0184R.attr.titleMarginTop, C0184R.attr.titleMarginBottom, C0184R.attr.titleMargins, C0184R.attr.maxButtonHeight, C0184R.attr.buttonGravity, C0184R.attr.collapseIcon, C0184R.attr.collapseContentDescription, C0184R.attr.navigationIcon, C0184R.attr.navigationContentDescription, C0184R.attr.logoDescription, C0184R.attr.titleTextColor, C0184R.attr.subtitleTextColor};
            View = new int[]{16842752, 16842970, C0184R.attr.paddingStart, C0184R.attr.paddingEnd, C0184R.attr.theme};
            ViewBackgroundHelper = new int[]{16842964, C0184R.attr.backgroundTint, C0184R.attr.backgroundTintMode};
            ViewStubCompat = new int[]{16842960, 16842994, 16842995};
            com_facebook_like_view = new int[]{2130772259, 2130772260, 2130772261, 2130772262, 2130772263, 2130772264};
            com_facebook_login_view = new int[]{2130772265, 2130772266, 2130772267, 2130772268};
            com_facebook_profile_picture_view = new int[]{2130772269, 2130772270};
        }
    }
}
